### ISSUE TITLE
entrypoint view shows a module present, but module view does not show entrypoint

### ISSUE THREAD

**Issue by cdaringe** [statoscope/statoscope#102]
**Describe the bug**

Greetings! In trying to diagnose an unexpected module, I wanted to use the feature landed in #89, so I:

- opened the entrypoint view
- observed a module that I did not expect, for example `use-delete-list-item.ts`. Below, you can observe the module present on the statoscope entrypoint page. Here's a screenshot from the entrypoint view of `pages/_app`, which is a next.js entrypoint:

![image](https://user-images.githubusercontent.com/1003261/132426529-98efe6d5-651b-4d38-a103-894609dc2a57.png)

- I then ctrl+click'd to drill down into the module view, but the module was missing from my entrypoints!

![image](https://user-images.githubusercontent.com/1003261/132426731-fbc120a0-824c-41a9-b0c9-915d0fb474e0.png)

So, a module showed up as associated with an entrypoint in one screen, but was _not associated_ with that same entrypoint in another view. Interestingly, the module (use-list-delete-item) show the `pages/_app` _chunk_ as a dependency? It doesn't make much sense to me, as I'm trying to reason about what this even means! 😄 

**To Reproduce**

I can reproduce it locally, but our application is very large, thus providing a MVP is rather challenging at the moment. I will dwell on how I may be able to reproduce. I can certainly share my _enormous_ 400MB stats.json :)

**Expected behavior**

One of the following is expected:

- the entrypoint view shall not render the module, **OR**
- the module view shall render the entrypoint

**Screenshots**

see above

**Versions**:
 - Node (for non-browser bug): 16.6.2 
 - Browser (for browser-bug):  n/a
 - Statoscope: 5.7.1

**Additional context**

- I have confirmed that by studying the `chunks` view and opening the `pages/_app` chunk, the offending module is _not_ present in the chunk. So, it's very puzzling as to why this module is being reported on the entrypoints page.
- I loaded the page as well in a browser, & I asserted that module of interest was **not** loaded/downloaded in any asset. This module _is_ in a library where a sibling module was imported and included. That is to say, something from this library was loaded, but _not this particular module_. Is it possible that additional filtering needs to occur before painting the boxes in the entrypoint page? `harmony side effect evaluation`'s, perhaps?

**Comment by smelukov** [comment]
@cdaringe Hi! Thank for the issue, I’ll investigate it ASAP ;)

**Comment by smelukov** [comment]
@cdaringe Could you share your stats.json with me? ☺️

**Comment by cdaringe** [comment]
Greetings, certainly. I apologize in advance for the large filesize.

[link to stats.json](https://drive.google.com/file/d/1NPLTUGbtEU_3nKRJsU2A62tm30tGQ48c/view?usp=sharing)

**Comment by smelukov** [comment]
@cdaringe Many thanks for the issue, I fixed it in 5.7.2 🎉 
The entry map has used an incorrect set of modules

**Comment by cdaringe** [comment]
Excellent, thank you very much. Was surprised that you were able to address it without a solid repo. I felt bad for not having a working demo

**Comment by smelukov** [comment]
@cdaringe hi! Is it work fine? ☺️

**Comment by cdaringe** [comment]
Greetings!

1. Yes, the entrypoints are now symmetric--I see the entrypoint on both views (the entrypoint view showing the module, and the module view showing the entrypoint)
2. I am still seeing a module present in statoscope which is not bundled anywhere. I was hoping statoscope would help show me the mapping between module => entrypoint => asset, but currently it's just tells me what entrypoint the module belongs to. I may need to provide some better information here to solve the issue_ However, the TLDR is that the foam graph says `use-delete-list-item.ts` is in use in the entrypoint, the module page even shows reasons (which appear incorrect, but that's may be a webpack thing not a statoscope thing??), and ultimately that module has _no content_ in any of the assets used for the entrypoint. So, it's puzzling. The tools are telling me a module is used in some capacity somewhere in my entrypoint--but it is 100% not.

**Comment by smelukov** [comment]
@cdaringe 
1) glad to read that ☺️
2) I used to came across this behaviour of weboack, but really want to understand is it the same case or is it statoscope bug :)
